[site]
title = "Lagrange"
description = "A pest-based markdown documentation renderer"
cname = "lagrange.docs.celestia.world"

[languages]
default = "en"
order = ["en", "zhs", "zht", "ja", "ko", "fr", "es", "ru", "ar"]
