name: Checks

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  check:
    runs-on: [self-hosted, linux, x64, local]
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - run: cargo fmt -p lagrange-library -- --check
      - run: cargo clippy --all-targets -- -D warnings
      - run: cargo test --all
